In [4]:
import numpy as np

arr = np.array([5,8,3,10])

print(arr)
print(type(arr))


[ 5  8  3 10]
<class 'numpy.ndarray'>


In [9]:
# Array Operations in Numpy

import numpy as np

arr_1 = np.array([5,8,3,10])
arr_2 = np.array([6,2,8,11])

result_addition = arr_1 + arr_2
print(result_addition)

result_subtraction = arr_1 - arr_2
print(result_subtraction)

result_multiplication = arr_1 * arr_2
print(result_multiplication)

result_division = arr_1 / arr_2
print(result_division)



[11 10 11 21]
[-1  6 -5 -1]
[ 30  16  24 110]
[0.83333333 4.         0.375      0.90909091]


In [10]:
# square root

import numpy as np

arr_1 = np.array([16,9,36,100])

print(np.sqrt(arr_1))

[ 4.  3.  6. 10.]


In [ ]:
print(np.sum(arr_1))  # sum

161


In [ ]:
print(np.mean(arr_1))  # mean = sum / length


40.25


In [15]:
print(np.max(arr_1))  # max
print(np.min(arr_1))  # min

100
9


In [16]:
# Mulitidimensional Arrays

import numpy as np

arr_1 = np.array([[5,8,3,10],[6,2,8,11]])

print(arr_1)

[[ 5  8  3 10]
 [ 6  2  8 11]]


In [ ]:
print(arr_1.size)  # number of single elements

8


In [ ]:
print(arr_1.ndim) # number of dimensions

2


In [ ]:
print(arr_1.shape)  # number of rows and columns - it is a tuple

(2, 4)


In [24]:
import numpy as np 

arr_1 = np.array([[[8,3,1],[5,9,8]],[[20,10,11],[6,4,3]]])

print(arr_1.shape)  # np.shape(arr_1) 

print(arr_1)

print(arr_1.ndim) # np.ndim(arr_1)
print(arr_1.size) # np.size(arr_1)




(2, 2, 3)
[[[ 8  3  1]
  [ 5  9  8]]

 [[20 10 11]
  [ 6  4  3]]]
3
12


In [28]:
import numpy as np

arr_1 = np.array([5,9,11,4,True])

print(arr_1)
print(arr_1.dtype)  # data type of array in numpy



[ 5  9 11  4  1]
int64


In [ ]:
# Array Indexing

import numpy as np

arr_1 = np.array([5,8,3,10])

print(arr_1[2])

arr_2 = np.array([[5,8,3,10],[6,2,8,11]])

print(arr_2[1][2])  #in Java
print(arr_2[1,2])  #in Python
print(arr_2[-2,-2]) #negative indexing

3
8
8
3


In [33]:
print(arr_2[1,2:4])
print(arr_2[1,2:])

[ 8 11]
[ 8 11]


In [ ]:
# Boolean Indexing

import numpy as np

arr_1 = np.array([5,8,3,10])

condition = arr_1 > 5  

print(condition)

[False  True False  True]


In [38]:
print(arr_1[condition]) #Imposing a condition
print(arr_1[arr_1 > 5])

[ 8 10]
[ 8 10]


In [45]:
arr = np.array([30,10,40,50,20])

#print(arr[arr < 40 and arr > 20])
print(arr[(arr < 40) & (arr > 25)])

[30]


In [51]:
# Q)  You are given the following array representing the body tempretures(in Celcious) of 5 patients or 3 timeslots(morning,afternoon,evening)

# 31 30 28
# 29 29 32
# 26 24 27
# 31 34 35
# 28 31 30

# Identify and extract all tempreture readings grater than the daily average tempreture using boolean indexing.



In [62]:
import numpy as np

temp_arr = np.array([
    [31,30,28],
    [29,29,32],
    [26,24,27],
    [31,34,35],
    [28,31,30]
    ])

print(temp_arr)

print(temp_arr.mean())

print(temp_arr > temp_arr.mean())

print(temp_arr[temp_arr > temp_arr.mean()])

[[31 30 28]
 [29 29 32]
 [26 24 27]
 [31 34 35]
 [28 31 30]]
29.666666666666668
[[ True  True False]
 [False False  True]
 [False False False]
 [ True  True  True]
 [False  True  True]]
[31 30 32 31 34 35 31 30]


In [68]:
import numpy as np

temp_arr = np.array([
    [31,30,28],
    [29,29,32],
    [26,24,27],
    [31,34,35],
    [28,31,30]
    ])

daily_average = np.mean(temp_arr)

print("Daily Average is:",daily_average)

print("all tempreture readings grater than the daily average tempreture using boolean indexing:"    ,temp_arr > daily_average)

print("Extract all tempreture readings grater than the daily average tempreture using boolean indexing:",temp_arr[temp_arr > daily_average])



Daily Average is: 29.666666666666668
all tempreture readings grater than the daily average tempreture using boolean indexing: [[ True  True False]
 [False False  True]
 [False False False]
 [ True  True  True]
 [False  True  True]]
Extract all tempreture readings grater than the daily average tempreture using boolean indexing: [31 30 32 31 34 35 31 30]


In [ ]:
# Array Initialization

import numpy as np

print(np.zeros((2,3))) #2D array
print(np.zeros(5)) #1D array

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]


In [70]:
import numpy as np

print(np.ones((2,3))) #2D array
print(np.ones(5)) #1D array

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [71]:
import numpy as np

print(np.full((2,3),5)) #2D array
print(np.full(5,5)) #1D array

[[5 5 5]
 [5 5 5]]
[5 5 5 5 5]


In [73]:
# Q2)

import numpy as np

print(np.full((2,3),[1,2,3]))

[[1 2 3]
 [1 2 3]]


In [74]:
import numpy as np

print(np.empty((2,3)))

[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-324 9.9e-324 1.5e-323]]


In [ ]:
#DataFrames

import pandas as pd

data = {'Name': ['Alice','Bob','Carlie','David'],
        'Age': [25,30,35,40]
        }

df = pd.DataFrame(data)

print(df)



     Name  Age
0   Alice   25
1     Bob   30
2  Carlie   35
3   David   40


In [ ]:
# Accessing by row label

import pandas as pd

print(df.loc[0,'Name'])


Alice


In [6]:
#Accessing by row index

import pandas as pd

print(df.iloc[2,1]) #iloc = integer location of location

35


In [7]:
# How to get rows by row lable...

import pandas as pd

print(df.loc[2])

Name    Carlie
Age         35
Name: 2, dtype: object


In [8]:
import pandas as pd

print(df.iloc[2])

Name    Carlie
Age         35
Name: 2, dtype: object


In [ ]:
# Accessing by row label

import pandas as pd


df = pd.DataFrame(data, index = ["Student 1","Student 2","Student 3","Student 4"])

print(df)

             Name  Age
Student 1   Alice   25
Student 2     Bob   30
Student 3  Carlie   35
Student 4   David   40


In [12]:
# Q3) 

import pandas as pd

print(df.iloc[1])
print(df.loc["Student 3"])

Name    Bob
Age      30
Name: Student 2, dtype: object
Name    Carlie
Age         35
Name: Student 3, dtype: object


In [18]:
# Q4)

import pandas as pd

#print(df.loc["Student 2" "Student 4"])

print(df.loc[["Student 2","Student 4"]])


            Name  Age
Student 2    Bob   30
Student 4  David   40


In [19]:
# Accessing by colomns

import pandas as pd

age_column = df['Age']

print(age_column)

Student 1    25
Student 2    30
Student 3    35
Student 4    40
Name: Age, dtype: int64


In [5]:
import pandas as pd

data = {'Name': ['Alice','Bob','Carlie','David'],
        'Age': [25,30,35,40]
        }
df = pd.DataFrame(data, index = ["Student 1","Student 2","Student 3","Student 4"])

print(df)
print(df.columns)
print(list(df.columns)) #converting to list

             Name  Age
Student 1   Alice   25
Student 2     Bob   30
Student 3  Carlie   35
Student 4   David   40
Index(['Name', 'Age'], dtype='object')
['Name', 'Age']


In [6]:
import pandas as pd

data = {'Name': ['Alice','Bob','Carlie','David'],
        'Age': [25,30,35,40]
        }
df = pd.DataFrame(data, index = ["Student 1","Student 2","Student 3","Student 4"])

print(df)
print(df.size)

             Name  Age
Student 1   Alice   25
Student 2     Bob   30
Student 3  Carlie   35
Student 4   David   40
8


In [ ]:
import pandas as pd

data = {'Name': ['Alice','Bob','Carlie','David'],
        'Age': [25,30,35,40]
        }
df = pd.DataFrame(data, index = ["Student 1","Student 2","Student 3","Student 4"])

8
(4, 2)
4


In [4]:
print(df.size)
print(df.shape)
print(len(df))

8
(4, 2)
4


In [ ]:
print(df.values)
print(type(df.values))  # To convert into numpy array


[['Alice' 25]
 ['Bob' 30]
 ['Carlie' 35]
 ['David' 40]]
<class 'numpy.ndarray'>


In [10]:
print(df['Age'].mean())
print(df['Age'].max())




32.5
40


In [8]:
print(df.sum())

Name    AliceBobCarlieDavid
Age                     130
dtype: object


In [13]:
df['City'] = ["Colombo","Kandy","Galle","Matara"]
df['Salary'] = [50000,60000,70000,80000]

print(df)

             Name  Age     City  Salary
Student 1   Alice   25  Colombo   50000
Student 2     Bob   30    Kandy   60000
Student 3  Carlie   35    Galle   70000
Student 4   David   40   Matara   80000


In [15]:
# Filtering rows in a DataFrame

filtered_df = df[df['Age'] > 30]

print(filtered_df)
print(type(filtered_df))

             Name  Age    City  Salary
Student 3  Carlie   35   Galle   70000
Student 4   David   40  Matara   80000
<class 'pandas.core.frame.DataFrame'>


In [24]:
# Q4) 

#filtered_df = df[df['Age'] > 28 and df['Salary'] > 65000]

filtered_df = df[(df['Age'] > 28) & (df['Salary'] < 65000)]

print(filtered_df)

          Name  Age   City  Salary
Student 2  Bob   30  Kandy   60000


In [ ]:
# Q) You are given the following data set representing the exam recod of students in a programming course.
# The data includes marks for two assignments and a final exam.
# StudentID   Name   Assignment1  Assignment2  Final
# 1001        Ayesha      78           60         70
# 1002        Nimal       65           65         75
# 1003        Tharindu    88           70          80
# 1004        Kasun       50           45          60
# 1005       Shashini     80           75         85     
 

# Write a python program using pandas to:
# 1. create a dataframe using the data given about 
# 2. display the names of all students who scored more than 80 in the final exam.
# 3. Compute the average scores each students across all three assesments and add it as a new column called "Average" in the dataframe.
# 4. Display the student(s)  with highest average score.
# 5. Calculate and display the total marks scored by all students in assigntment 1.



In [ ]:
import pandas as pd

# 1)
student_data = {'StudentId': [1001,1002,1003,1004,1005],
              'Name' : ['Ayesha','Nimal','Tharindu','Kasun','Shashini'],
              'Assignment1' : [78,65,88,50,80],
              'Assignment2' : [85,70,90,45,75],
              'Final' : [90,72,95,60,85]
              }
# 2)
df = pd.DataFrame(student_data)
print(df)

filtered_df = df[df['Final'] > 80 ]
print(filtered_df[['Name','Final']])

# 3)
#Average_df = df[df['Assignment1'] + df['Assignment2'] + df['Final']]/3
df['Average'] = (df['Assignment1'] + df['Assignment2'] + df['Final'])/3
print(df)

# 4) 
average_max = df['Average'].max()
max_average_df = df[df['Average'] == average_max]
print(max_average_df[['Name','Average']])


# 5)
print(df['Assignment1'].sum())



   StudentId      Name  Assignment1  Assignment2  Final
0       1001    Ayesha           78           85     90
1       1002     Nimal           65           70     72
2       1003  Tharindu           88           90     95
3       1004     Kasun           50           45     60
4       1005  Shashini           80           75     85
       Name  Final
0    Ayesha     90
2  Tharindu     95
4  Shashini     85
   StudentId      Name  Assignment1  Assignment2  Final    Average
0       1001    Ayesha           78           85     90  84.333333
1       1002     Nimal           65           70     72  69.000000
2       1003  Tharindu           88           90     95  91.000000
3       1004     Kasun           50           45     60  51.666667
4       1005  Shashini           80           75     85  80.000000
       Name  Average
2  Tharindu     91.0
361


In [62]:
# Read CSV File

import pandas as pd

df = pd.read_csv("test.csv")
print(df)
print(type(df))

          Name  Age Occupation
0     John Doe   30   Engineer
1   Jane Smith   25    Teacher
2  Bob Johnson   40     Doctor
3  Alice Brown   35     Artist
<class 'pandas.core.frame.DataFrame'>


In [ ]:
# JSON File